### PR TITLE
solve #196 need julia >= v0.5.1

### PR DESCRIPTION
**Pull request by oxinabox**
This solves #196 
Make sure no-one is on julia 0.5.0

### CODE REVIEW

**Comment by malmaud** [comment]
Oh hmm, I don't really want to leave the .5 users in the cold over such a small thing. Why don't we just have an if statement that loads the old version of get_def_graph if users are `<0.5.1`, and eventually we'll delete that block?

**Comment by oxinabox** [comment]
0.5.0 -> 0.5.1 is a really trivial upgrade.
It took me 2 minutes to download the newer release, for linux.

It is not like 0.5.0 is in package managers, and 0.5.1 is not.
0.4.5 is in debian's repo.

I believe @staticfloat's PPA has 0.5.1,
(https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases/)

and in Homebrew is is 0.5.1 for sure https://github.com/staticfloat/homebrew-julia

Anyone who needs 0.5.0 can just stay with using the last tagged Tensorflow release,
prior to the changes to `@with_def_graph`
It is pretty functional.
And 0.6 is just around the corner.

Alternatively, I think it can be changed in a way that works for 0.5.0 and 0.5.1 easily enough.
But I don't care to have two different patch versions of julia installed to find it.
(I'm thinking it is to delete the semicolon from the call, when there are no keyword-arguments. But not tested that)

**Comment by malmaud** [comment]
We will eventually have a branch that only works on Julia 0.6, but I at least want the next tagged version of TensorFlow to still work on .5.0. 

Some people have Julia installed by system administrators on clusters or might otherwise be annoyed to have to upgrade Julia to .5.1, even if (as I agree) it's simple, so I'm still reluctant to require people to upgrade to .5.1.

**Comment by malmaud** [comment]
I'm going to close in favor of https://github.com/malmaud/TensorFlow.jl/commit/3d8b91c76b14e97e1282172b2db1966b52277602 for now, but we can delete this once we have a Julia .6 branch.

**Comment by oxinabox** [comment]
fair enough.

**Pull request closed without merging**
