### PR TITLE
tf.select on lstm state tuple

### PR DESCRIPTION
**Pull request by gustafsson**
to support dynamic length rnn

### CODE REVIEW

**Comment by oxinabox** [comment]
Can you explain a bit more the motivation of this change?
The first file changed is a matter of style. (idk which is clearer).
The second defines an operation but its not being used for anything in this PR.


More broadly welcome and hello, thank you for your contributions.
I've just taken a quick look at each of them.
Come say high in the #machine-learning channel on the JuliaLang slack: http://slackinvite.julialang.org/

**Comment by gustafsson** [comment]
The change about `new_state` and `new_output` should have been in #366. I've reverted that commit. Also see https://github.com/malmaud/TensorFlow.jl/pull/366#issuecomment-373688170

**Comment by gustafsson** [comment]
If sequences have varying lengths given by the `sequence_length` argument then the `rnn` function uses `select` to skip updating states after the end of the input sequence. But `select` works on tensors and the state of an LSTM cell is a tuple of two tensors.

This PR makes it possible to select one of two LSTM state tuples based on some condition.

**Comment by gustafsson** [comment]
Thanks for the invite, I'll pop by on slack to say hi!

**Comment by oxinabox** [comment]
So are you saying dynamic length was broken for LSTM?

**Comment by gustafsson** [comment]
yes

**Comment by oxinabox** [comment]
Ahh now I understand what this PR is for.
 I think that would be my fault -- I use GRU more than LSTM.
 I will review this later.

**Comment by gustafsson** [comment]
I should have mentioned that I was getting an error on this row for LSTM cells: https://github.com/malmaud/TensorFlow.jl/blob/fcf8300257a6b96940fd1d04985ea6d9d2fce0b0/src/ops/nn.jl#L77

**Comment by gustafsson** [comment]
Np, thank you!

**Pull request merged**
