### PR TITLE
Remove Distributions dependence

### PR DESCRIPTION
**Pull request by malmaud**

### CODE REVIEW

**Comment by oxinabox** [comment]
Are you happy with the name `DefaultInitializer`
I kinda think we might as well go full in and say `RandomNormalInitializer` 
and maybe even give it a variance field (default to 0.01)

**Comment by malmaud** [comment]
Ya I suppose. My thinking was I didn't want to duplicate stuff already in Distributions, but this would be so minor.

**Comment by oxinabox** [comment]
It is probably worth mentioning in the docs / docstrings that any continuous distribution from Distributions.jl is a viable initializer

**Comment by oxinabox** [comment]
I just rebased this because JLD.jl was borking CI,

**Comment by oxinabox** [comment]
Moved Distributions and MNIST into test dependencies.
In julia 0.7 someone who installed TensorFlow.jl 
would not have access to MNIST from there environment anyway, unless they installed it separately.

**Comment by malmaud** [comment]
I'm restarting the failed job

**Pull request merged**
