### PR TITLE
Update ErrMsg text from TensorFlow in core.jl

### PR DESCRIPTION
**Pull request by rickhg12hs**
Fixes one test with current libtensorflow.so.

### CODE REVIEW

**Comment by malmaud** [comment]
cc @oxinabox, who wrote that test.

**Comment by rickhg12hs** [comment]
Hmmmm, it looks like Travis's `libtensorflow.so` is different.  After my edit, the test passes on my machines.

**Comment by oxinabox** [comment]
we could remove the try-catch and just use a `@test_throws`
I wanted to be more specific for some reason there.
But if tensorflow is going to keep changing the error messages from version to version...

**Comment by rickhg12hs** [comment]
It looks like the error/exception message came from a TensorFlow Python (???) file that was updated just a few months ago.  It seems that some SVD gradients are supported now.

https://github.com/tensorflow/tensorflow/blame/b3d5ec90bc6b7ae7822ea82d82b41e529c5e047a/tensorflow/python/ops/linalg_grad.py#L267

I'm missing the "big picture" here.  How does a Python exception message get emitted from a Julia program?

**Comment by oxinabox** [comment]
> I'm missing the "big picture" here. How does a Python exception message get emitted from a Julia program?

Most of TensorFlow.jl,   is either fully written in julia (e.g shape inference, all the RNN stuff),
or backing on to code in the TensorFlow C api.

The exception to this is the `gradients` function.
That falls back on the Python API. See #20.

**Comment by oxinabox** [comment]
Anyway, I think that whole testset can just be deleted.

**Comment by oxinabox** [comment]
I am pretty sure this was solved elsewhere now.

**Pull request closed without merging**
