### PR TITLE
add batch_matmul

### PR DESCRIPTION
**Pull request by baggepinnen**

### CODE REVIEW

**Comment by malmaud** [comment]
Thanks! Can you add a test and documentation?

**Comment by malmaud** [comment]
Can you rebase this?

**Comment by baggepinnen** [comment]
I tried to rebase this, but since I have no idea what I am doing, I might have screwed things up tremendously =/

**Comment by malmaud** [comment]
Hmm, I think the rebase didn't go so well. Do you want to submit the original PR and I'll rebase it on my side?

**Comment by baggepinnen** [comment]
see #164 , I hope that is a bit less messy

**Comment by malmaud** [comment]
Superseded by https://github.com/malmaud/TensorFlow.jl/pull/164

**Pull request closed without merging**
