### PR TITLE
Typos and version used

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Review by oxinabox — APPROVED** [review]

**Comment by PallHaraldsson** [comment]
That was quick, but there's another one, "maintenance" and more serious issue.

**Comment by PallHaraldsson** [comment]
While you're here, should this package state something stronger than "TensorFlow.jl is in minimal maintenance mode", it's very minimal as in zero, and 1.15.5 has security issue and the issue before. I'm not sure it applies to this package, even if the older versions are also affected.

**Comment by PallHaraldsson** [comment]
Say something like: "TensorFlow.jl uses 1.13.x and no update to the wrapper is planned, while current official versions are 2.x and 1.15.x"?

I'm not sure if something like that is enough.

https://github.com/tensorflow/tensorflow/releases/tag/v2.4.1

Tensorflow.jl is in minimal maintance mode"

**Comment by PallHaraldsson** [comment]
Maybe just merge this now as is?

**Comment by PallHaraldsson** [comment]
Just merge this? Was approved before I added the version info.

**Comment by malmaud** [comment]
Sure thanks, sorry for the delay.

**Pull request merged**
