### PR TITLE
[WIP] Exporting and Importing a MetaGraph

### PR DESCRIPTION
**Pull request by yeesian**
For my reference: https://www.tensorflow.org/how_tos/meta_graph/ and https://www.tensorflow.org/how_tos/tool_developers/

### CODE REVIEW

**Comment by yeesian** [comment]
I'm stumped. Suppose I generate `my-model.meta` (in a python session) by running

```python
# based on the example in https://www.tensorflow.org/how_tos/meta_graph/
import tensorflow as tf
import math

images = tf.fill([100,28], 1.2)
with tf.name_scope("hidden1"):
  weights = tf.Variable(
      tf.truncated_normal([28, 128],
                          stddev=1.0 / math.sqrt(float(28))),
      name="weights")
  biases = tf.Variable(tf.fill([128], 0.0),
                       name="biases")
  hidden1 = tf.nn.relu(tf.matmul(images, weights) + biases)
# Hidden 2
with tf.name_scope("hidden2"):
  weights = tf.Variable(
      tf.truncated_normal([128, 32],
                          stddev=1.0 / math.sqrt(float(128))),
      name="weights")
  biases = tf.Variable(tf.fill([32], 0.0),
                       name="biases")
  hidden2 = tf.nn.relu(tf.matmul(hidden1, weights) + biases)
# Linear
with tf.name_scope("softmax_linear"):
  weights = tf.Variable(
      tf.truncated_normal([32, 10],
                          stddev=1.0 / math.sqrt(float(32))),
      name="weights")
  biases = tf.Variable(tf.fill([10], 0.0),
                       name="biases")
  logits = tf.matmul(hidden2, weights) + biases
  tf.add_to_collection("logits", logits)

init_all_op = tf.global_variables_initializer()

with tf.Session() as sess:
  # Initializes all the variables.
  sess.run(init_all_op)
  # Runs to logit.
  sess.run(logits)
  # Creates a saver.
  saver0 = tf.train.Saver()
  saver0.save(sess, 'my-model')
  # Generates MetaGraphDef.
  saver0.export_meta_graph('my-model.meta')
```
and then load it in julia (on this branch):
```julia
using TensorFlow; const TF = TensorFlow
sess = Session()
# reads the file into a `TF.tensorflow.MetaGraphDef` protobuf object
metagraphdef = read_meta_graph_file("my-model.meta")
# imports the information from `metagraphdef` into the session
saver = TF.train.import_meta_graph(metagraphdef)
```

We can create a `TF.tensorflow.MetaGraphDef` based on the current session:
```
sess_metagraphdef = TF.train.create_meta_graph_def()
```
But nothing gets written out from `sess_metagraphdef` by `writeproto`:
```julia
julia> using ProtoBuf

julia> writeproto(PipeBuffer(), sess_metagraphdef)
0
```
even though it is non-empty in its `collection_def` and `graph_def` fields:
```
julia> sess_metagraphdef.collection_def
Dict{AbstractString,TensorFlow.tensorflow.CollectionDef} with 4 entries:
  "TrainableVariables" => TensorFlow.tensorflow.CollectionDef(#undef,TensorFlow…
  "QueueRunners"       => TensorFlow.tensorflow.CollectionDef(#undef,TensorFlow…
  "Summaries"          => TensorFlow.tensorflow.CollectionDef(#undef,TensorFlow…
  "Variables"          => TensorFlow.tensorflow.CollectionDef(#undef,TensorFlow…

julia> sess_metagraphdef.collection_def["TrainableVariables"]
TensorFlow.tensorflow.CollectionDef(#undef,TensorFlow.tensorflow.CollectionDef_BytesList(Array{UInt8,1}[UInt8[0x0a,0x0f,0x68,0x69,0x64,0x64,0x65,0x6e,0x31,0x2f  …  0x74,0x61,0x69,0x6e,0x65,0x72,0x12,0x02,0x12,0x00],UInt8[0x0a,0x16,0x68,0x69,0x64,0x64,0x65,0x6e,0x31,0x2f  …  0x6f,0x63,0x6b,0x69,0x6e,0x67,0x12,0x02,0x28,0x01],UInt8[0x0a,0x0f,0x68,0x69,0x64,0x64,0x65,0x6e,0x32,0x2f  …  0x74,0x61,0x69,0x6e,0x65,0x72,0x12,0x02,0x12,0x00],UInt8[0x0a,0x16,0x68,0x69,0x64,0x64,0x65,0x6e,0x32,0x2f  …  0x6f,0x63,0x6b,0x69,0x6e,0x67,0x12,0x02,0x28,0x01],UInt8[0x0a,0x15,0x73,0x6f,0x66,0x74,0x6d,0x61,0x78,0x5f  …  0x74,0x61,0x69,0x6e,0x65,0x72,0x12,0x02,0x12,0x00],UInt8[0x0a,0x1c,0x73,0x6f,0x66,0x74,0x6d,0x61,0x78,0x5f  …  0x6f,0x63,0x6b,0x69,0x6e,0x67,0x12,0x02,0x28,0x01],UInt8[0x0a,0x16,0x73,0x6f,0x66,0x74,0x6d,0x61,0x78,0x5f  …  0x74,0x61,0x69,0x6e,0x65,0x72,0x12,0x02,0x12,0x00],UInt8[0x0a,0x1d,0x73,0x6f,0x66,0x74,0x6d,0x61,0x78,0x5f  …  0x6f,0x63,0x6b,0x69,0x6e,0x67,0x12,0x02,0x28,0x01],UInt8[0x0a,0x0e,0x68,0x69,0x64,0x64,0x65,0x6e,0x31,0x2f  …  0x74,0x61,0x69,0x6e,0x65,0x72,0x12,0x02,0x12,0x00],UInt8[0x0a,0x15,0x68,0x69,0x64,0x64,0x65,0x6e,0x31,0x2f  …  0x6f,0x63,0x6b,0x69,0x6e,0x67,0x12,0x02,0x28,0x01],UInt8[0x0a,0x0e,0x68,0x69,0x64,0x64,0x65,0x6e,0x32,0x2f  …  0x74,0x61,0x69,0x6e,0x65,0x72,0x12,0x02,0x12,0x00],UInt8[0x0a,0x15,0x68,0x69,0x64,0x64,0x65,0x6e,0x32,0x2f  …  0x6f,0x63,0x6b,0x69,0x6e,0x67,0x12,0x02,0x28,0x01]]),#undef,#undef,#undef)
```
```
julia> sess_metagraphdef.graph_def
TensorFlow.tensorflow.GraphDef(TensorFlow.tensorflow.NodeDef[name: Fill/dims
op: Const
attr {
  key: dtype
  value {
    type: Int32
  }
}
attr {
  key: _class
  value {
      }
}
attr {
  key: value
  value {
    dtype: Int32
    shape: [2]
    content: UInt8[0x64,0x00,0x00,0x00,0x1c,0x00,0x00,0x00]
  }
}
```
If it helps, here's a [link](https://www.dropbox.com/s/l7mzr08bg6f5fty/my-model.meta?dl=0) to a copy of `my-model.meta`

cc: @tanmaykm

**Comment by tanmaykm** [comment]
Looking into it...

@yeesian I see the below error on a fresh setup, with TensorFlow checked out to this branch. Do I need to do something more to get it to compile?

````
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using TensorFlow
INFO: Precompiling module TensorFlow.
WARNING: could not import Base.lastidx into LegacyStrings
ERROR: InitError: On worker 2:
The Python TensorFlow package could not be imported. You must install Python TensorFlow before using this package.
 in init at /home/tan/.julia/v0.5/TensorFlow/src/py.jl:12
 in #1 at /home/tan/.julia/v0.5/TensorFlow/src/TensorFlow.jl:116
 in #629 at ./multi.jl:1428
 in run_work_thunk at ./multi.jl:1001
 in run_work_thunk at ./multi.jl:1010 [inlined]
 in #597 at ./event.jl:68
 in #remotecall_wait#611(::Array{Any,1}, ::Function, ::Function, ::Base.Worker, ::String, ::Vararg{String,N}) at ./multi.jl:1095
 in remotecall_wait(::Function, ::Base.Worker, ::String, ::Vararg{String,N}) at ./multi.jl:1086
 in #remotecall_wait#614(::Array{Any,1}, ::Function, ::Function, ::Int64, ::String, ::Vararg{String,N}) at ./multi.jl:1105
 in remotecall_wait(::Function, ::Int64, ::String, ::Vararg{String,N}) at ./multi.jl:1105
 in eval(::Module, ::Any) at ./boot.jl:234
 in load_python_process() at /home/tan/.julia/v0.5/TensorFlow/src/TensorFlow.jl:113
 in __init__() at /home/tan/.julia/v0.5/TensorFlow/src/TensorFlow.jl:105
 in _include_from_serialized(::String) at ./loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 in require(::Symbol) at ./loading.jl:423
during initialization of module TensorFlow
````

**Comment by tanmaykm** [comment]
@yeesian something like the below version of `create_meta_graph_def` should work:

````
function create_meta_graph_def(graph::Graph)
    # reference: https://github.com/tensorflow/tensorflow/blob/cd1fe4072b43e650d47187838b7a37b050ec3d75/tensorflow/python/framework/meta_graph.py#L309-L385
    graph_def = readproto(
        PipeBuffer(get_proto(graph)),
        tensorflow.GraphDef()
    )
    meta_info_def = tensorflow.MetaGraphDef_MetaInfoDef()
      # TODO: Set the tf version strings to the current tf build.
      # meta_graph_def.meta_info_def.tensorflow_version = versions.__version__
      # meta_graph_def.meta_info_def.tensorflow_git_version = versions.__git_version__
    collection_def = Dict{String,tensorflow.CollectionDef}()
    # In general, we should provide a registration mechanism for `to_proto`
    # functions to serialize objects into their corresponding protocol buffers.
    # (see https://github.com/tensorflow/tensorflow/blob/799e31f3840c21322e380e1ec6e5bacb95d016fa/tensorflow/python/framework/ops.py#L4277-L4300)
    # (and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/meta_graph.py#L274-L282)
    for (collectionname, collection) in graph.collections
        bytes_list = Array{UInt8,1}[]
        for obj in collection
            # TODO: complete it for the other types
            if isa(obj, Variable)
                push!(bytes_list, get_proto(obj.var_node))
                push!(bytes_list, get_proto(obj.assign_node))
            elseif isa(obj, Tensor)
                push!(bytes_list, get_proto(obj.op))
            end
        end
        collectiondef = tensorflow.CollectionDef(;bytes_list=tensorflow.CollectionDef_BytesList(;value=bytes_list))
        collection_def[string(collectionname)] = collectiondef
    end
    meta_graph_def = tensorflow.MetaGraphDef(; graph_def=graph_def, meta_info_def=meta_info_def, collection_def=collection_def)
    meta_graph_def
end
````

ProtoBuf does not serialize fields that are not marked as 'filled'. One way to mark them such is through the constructor as above. (`set_field!` does it too)

**Comment by yeesian** [comment]
> ProtoBuf does not serialize fields that are not marked as 'filled'. One way to mark them such is through the constructor as above. (`set_field!` does it too)

That clarifies, and your proposed solution works for me. Thanks!

**Comment by malmaud** [comment]
OK, I've rebased this and copied the branch to this repository. Thanks for working on this, much appreciated!

**Comment by yeesian** [comment]
Thanks for taking over! 👍

I had been falling behind development here.

**Pull request closed without merging**
