### PR TITLE
Wrapped more image functions, added tests

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by malmaud** [comment]
Looks like CI is failing for the last commit https://travis-ci.org/malmaud/TensorFlow.jl/jobs/165675935

**Comment by kshyatt** [comment]
It's the `grayscale` test. It's claiming the node name doesn't exist even though it works in Python! Grrr. Should I comment the test out for now, or what?

**Comment by malmaud** [comment]
I guess we should comment out the test and the `grayscale` function for now. I'll investigate soon.

**Comment by malmaud** [comment]
Hmm so looking at the graph definition the python API generates, it seems like a lot of these functions are actually implemented on the Python side as a sequence of TensorFlow operations rather than corresponding to a single one. For example, for `rgb_to_grayscale`:

```
node {
  name: "Placeholder"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
}
node {
  name: "rgb_to_grayscale/Identity"
  op: "Identity"
  input: "Placeholder"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "rgb_to_grayscale/Rank"
  op: "Rank"
  input: "Placeholder"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "rgb_to_grayscale/sub/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "rgb_to_grayscale/sub"
  op: "Sub"
  input: "rgb_to_grayscale/Rank"
  input: "rgb_to_grayscale/sub/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "rgb_to_grayscale/ExpandDims/dim"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "rgb_to_grayscale/ExpandDims"
  op: "ExpandDims"
  input: "rgb_to_grayscale/sub"
  input: "rgb_to_grayscale/ExpandDims/dim"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "Tdim"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "rgb_to_grayscale/mul/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "l\t\231>\242E\026?\325x\351="
      }
    }
  }
}
node {
  name: "rgb_to_grayscale/mul"
  op: "Mul"
  input: "rgb_to_grayscale/Identity"
  input: "rgb_to_grayscale/mul/y"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "rgb_to_grayscale/Sum"
  op: "Sum"
  input: "rgb_to_grayscale/mul"
  input: "rgb_to_grayscale/ExpandDims"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: true
    }
  }
}
node {
  name: "rgb_to_grayscale"
  op: "Identity"
  input: "rgb_to_grayscale/Sum"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
versions {
  producer: 15
}
```

**Comment by malmaud** [comment]
Superseded by https://github.com/malmaud/TensorFlow.jl/pull/71

**Pull request closed without merging**
