### PR TITLE
Fix broadcasting

### PR DESCRIPTION
**Pull request by oxinabox**
Broadcasting has been broken since 0.6 came out.
This implements @MikeInnes 's work around.

### CODE REVIEW

**Comment by oxinabox** [comment]
This needs top wait for https://github.com/MikeInnes/TakingBroadcastSeriously.jl/pull/6
to be merged, and tagged, and then it needs it's REQUIRE file to be updated to match

**Comment by MikeInnes** [comment]
FYI https://github.com/JuliaLang/METADATA.jl/pull/11608

**Comment by malmaud** [comment]
Is this ready to be merged?

**Comment by oxinabox** [comment]
I believe so. I'll just retrigger travis

**Comment by malmaud** [comment]
Yay it passes

**Pull request merged**
